### ISSUE TITLE
Improve Language Tour to communicate that `if` guard clause can't take functions

### ISSUE THREAD

**Issue by erikareads** [gleam-lang/try-gleam#1]
The current language tour doesn't communicate that you can't use functions in a guard clause:
https://gleam.run/book/tour/case-expressions.html#checking-equality-and-ordering-in-pattern

I think there's an implicit "only" here, that should be made explicit:

> The guard expression can check for equality or ordering for Int and Float.

**Comment by lpil** [comment]
Thank you
